#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa
spec:
  selector:
    matchLabels:
      app: uaa-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: uaa-deployment
    spec: #! pod spec
      containers:
        - name: uaa
          image: "cfidentity/uaa@sha256:93b70b26fbb3de88d93728b0daf1ea7b001fde89a24e283c3db36bf4c6af087c"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: spring_profiles
              value: "default,hsqldb"
            - name: UAA_CONFIG_PATH
              value: /etc/config
          volumeMounts:
          - name: uaa-config
            mountPath: /etc/config
      volumes:
      - name: uaa-config
        configMap:
          name: uaa-config